(define (read-words)
  (let ((word (read (current-input-port))))
    (if (eof-object? word)
        '()
        (cons (or (and (symbol? word)
                       (symbol->string word))
                  (and (number? word)
                       (number->string word)))
              (read-words)))))