(load "trace.rkt")
(define (selection-sort pred? xs)
  (define (delited xs a)
    (cond ((null? xs) '())
          ((eq? a (car xs)) (cdr xs))
          (else (cons (car xs) (delited (cdr xs) a)))))
  (define (help xs a)
    (cond ((null? xs) a)
          ((pred? (car xs) a) (help (cdr xs) (car xs)))
          (else (help (cdr xs) a))))
  (if (null? xs)
      '()
      (cons (help xs (car xs)) (selection-sort pred? (delited xs (help xs (car xs)))))))

(define (insertion-sort pred? xss)
  (define (vstavka xs a k)
    (cond ((null? xs) (cons a '()))
          ((= k 1) (cons a xs))
          (else (cons (car xs) (vstavka (cdr xs) a (- k 1))))))
  (define (help1 ys a k)
    (cond ((null? ys) k)
          ((not (pred? (car ys) a)) k)
          (else (help1 (cdr ys) a (+ k 1)))))
  (define (help2 xs ss)
    (if (null? xs) ss (help2 (cdr xs) (vstavka ss (car xs) (help1 ss (car xs) 1)))))
  (help2 xss '()))